/*
 * File: app/view/LightPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LightPanel', {
    extend: 'Ext.carousel.Carousel',
    alias: 'widget.lightpanel',

    config: {
        flex: 1,
        direction: 'vertical',
        items: [
            {
                xtype: 'container',
                itemId: 'light-0',
                style: 'background:#000000;'
            },
            {
                xtype: 'container',
                itemId: 'light-25',
                style: 'background:#444444;'
            },
            {
                xtype: 'container',
                itemId: 'light-50',
                style: 'background:#888888;'
            },
            {
                xtype: 'container',
                itemId: 'light-75',
                style: 'background:#CCCCCC;'
            },
            {
                xtype: 'container',
                itemId: 'light-100',
                style: 'background:#FFFFFF;'
            }
        ]
    }

});